### ISSUE TITLE
How customize it ?

### ISSUE THREAD

**Issue by shortymc** [marcmascarell/Vuindows#13]
Waw !
It's really great work !

I want to change, add/remove icons and associates links.
How i can do for personalize interface.
I've beautified vendor.js and app.js
but i think it's not enough for modifying the desktop.

 Best regards.

**Comment by shortymc** [comment]
Hi.
I've tried to make changes in program.js
but nothing changes in homepage
i try reupload with changes and nothing change in the homepage
also i can't see audio and videos icons and apps
![Capture d’écran_2021-05-12_01-07-08](https://user-images.githubusercontent.com/10462908/117895385-88961680-b2be-11eb-8e4e-71587f00d11c.png)

` 
<template>
    <div v-show="! minimized"
         class="Program"
         :class="{
            'Program--maximized': maximized,
            'Program--minimized': minimized,
         }"
         :style="{
            zIndex
         }"
         draggable="false"
         @mousedown="bringProgramToTop(id)">
        <div class="Program__header" @dblclick="toggleMaximize">
            <div class="Program__title">
                <img class="Program__icon" :src="program.icon" alt="" width="18" height="18">

                {{ title }}
            </div>

            <div class="Program__windowControls">
                <div class="Program__windowControls__control" @click="minimize">
                    <i class="icon ion-ios-minus-empty"></i>
                </div>

                <div v-if="isMaximizable"
                     class="Program__windowControls__control"
                     @click="toggleMaximize">
                    <i v-if="maximized" class="icon ion-ios-photos-outline" style="font-size: .8em"></i>
                    <svg v-else
                         x="0px" y="0px" viewBox="0 0 10.2 10.1" data-radium="true" style="width: 10px; height: 10px;"><path  d="M0,0v10.1h10.2V0H0z M9.2,9.2H1.1V1h8.1V9.2z"></path></svg>
                </div>

                <div class="Program__windowControls__control Program__windowControls__control--danger" @click="terminateProgram(id)">
                    <svg x="0px" y="0px" viewBox="0 0 10.2 10.2" data-radium="true" style="width: 10px; height: 10px;"><polygon  points="10.2,0.7 9.5,0 5.1,4.4 0.7,0 0,0.7 4.4,5.1 0,9.5 0.7,10.2 5.1,5.8 9.5,10.2 10.2,9.5 5.8,5.1 "></polygon></svg>
                </div>
            </div>
        </div>

        <nav v-if="$slots['menu']" class="Program__menu">
            <slot name="menu"></slot>
        </nav>

        <div class="Program__content" :class="{'Program__content--scrollable': options.scrollable}">
            <slot name="content"></slot>
        </div>
    </div>
</template>

<script>
    import { mapActions, mapGetters } from 'vuex';

    export default {
        data() {
            return {
                defaultOptions: {
                    resizable: true,
                    draggable: true,
                    maximizable: true,
                    scrollable: true,
                    size: {
                        width: null,
                        height: null,
                    },
                    position: {
                        left: null,
                        top: null,
                    },
                    mode: 'normal', // 'normal', 'minimized', 'maximized'
                    previousMode: null // When recovering from minimized
                },
                id: null
            }
        },
        props: {
            title: {
                type: String,
                required: true
            }
        },
        beforeMount() {
            this.id = this.$parent.id;

            this.setProgramOptions({
                id: this.id,
                options: _.merge({}, this.defaultOptions, this.$parent.options)
            });
        },
        mounted() {
            const $vm = this;
            const $jqueryElement = $(this.$el);

            if (this.options.draggable) {
                $jqueryElement.draggable({
                    handle: ".Program__header",
                    cancel: ".Program__windowControls",
                    containment: ".desktop",
                    scroll: false,
                    stop: function(event, ui) {
                        $vm.updateOptions({
                            position: {
                                left: ui.position.left + 'px',
                                top: ui.position.top + 'px',
                            }
                        });
                    }
                });
            }

            if (this.options.resizable) {
                $jqueryElement.resizable({
                    containment: ".desktop",
                    minHeight: 300,
                    minWidth: 300,
                    stop: function(event, ui) {
                        $vm.updateOptions({
                            size: {
                                width: ui.size.width + 'px',
                                height: ui.size.height + 'px',
                            }
                        });
                    }
//                aspectRatio: 16 / 9
                });
            }
        },
        computed: {
            ...mapGetters([
                'getRunningProgram',
            ]),
            program() {
                return this.getRunningProgram(this.id)
            },
            options() {
                return this.program.options;
            },
            maximized() {
                return this.options.mode === 'maximized';
            },
            minimized() {
                return this.options.mode === 'minimized';
            },
            isMaximizable() {
                return this.options.maximizable;
            },
            zIndex() {
                return this.program.zIndex;
            },
            mode() {
                return this.options.mode;
            },
        },
        methods: {
            ...mapActions([
                'terminateProgram',
                'bringProgramToTop',
                'setProgramOptions',
            ]),
            updateOptions(options) {
                this.setProgramOptions({
                    id: this.id,
                    options: _.merge({}, this.options, options)
                });
            },
            toggleMaximize() {
                this.updateOptions({
                    mode: this.maximized ? 'normal' : 'maximized'
                });

                if (this.maximized) {
                    this.$el.style.left = 0;
                    this.$el.style.top = 0;
                    this.$el.style.right = 0;
                } else {
                    this.$el.style.left = this.options.position.left;
                    this.$el.style.top = this.options.position.top;
                    this.$el.style.right = null;
                }
            },
            minimize() {
                this.updateOptions({
                    mode: 'minimized',
                    previousMode: this.mode
                })
            }
        }
    }
</script>

<style lang="scss" rel="stylesheet/scss">
    .Program,
    .popupShell {
        display: flex;
        flex-direction: column;
        position: absolute;
        height: 40em;
        width: 60%;
        z-index: 10;
        animation: fade-and-scale .2s;
        overflow: hidden;
        background-color: white;
        box-sizing: border-box;
        box-shadow: rgba(0, 0, 0, 0.2) 0 2px 11px 3px;
        border-width: 1px;
        border-style: solid;
        border-color: rgb(170, 170, 170);
        user-select: none;
        cursor: default;

        &__header {
            position: relative; // Improves draggability
            display: flex;
            align-items: center;
            color: black;

            width: 100%;
            height: 31px;
            min-height: 31px;

            background-color: white;
            visibility: visible;

            user-select: none;
            -webkit-app-region: drag;
            cursor: default;
        }

        &__title {
            flex: 1;
            margin-left: 1em;
            font-size: .95em;
            display: flex;
            align-items: center;
        }

        &__icon {
            margin-right: .5em;
        }

        &__menu  {
            height: 1.5em;
            display: flex;
            border-bottom: 1px solid #ccc;

            div {
                width:4em;
                text-align: center;
                line-height: 1.5em;
            }

            div:nth-child(1) {
                background: dodgerblue;
                color:white;
            }
        }

        &__windowControls {
            display: flex;
            align-items: center;
            height: 31px;

            &__control {
                font-size: 1.3em;
                display: flex;
                height: 100%;
                align-items: center;
                justify-content: center;
                width: 46px;
                transition: background-color 0.1s;
                text-align: center;

                &:hover {
                    background-color: rgb(229, 229, 229);
                }

                &--danger {
                    &:hover {
                        background-color: red;

                        svg {
                            fill: white;
                        }
                    }
                }
            }
        }

        &__content {
            flex: 1;

            &--scrollable {
                overflow: auto;
            }
        }

        &--autoHeight {
            height: auto;

            .Program__content,
            .popupShell__content {
                height: auto;
            }
        }

        &--maximized {
            /*bottom: 2.7em;*/
            height: calc(100%) !important;
            width: 100% !important;
            /*width: calc(100% - .2em) !important;*/
            animation: .2s fade-and-slide;
        }

        &--minimized {
            display: none;
        }
    }

</style>

 Thanks for your support.
Best regards
 `

**Comment by shortymc** [comment]
Vuindows is so great   :1st_place_medal:
I just wan't to changes icons and their links. 
please help me !!

Best regards

**Comment by marcmascarell** [comment]
Hi,

Glad you like it!

I updated some dependencies.

About modifying `Desktop.vue` shortcuts there is a computed property called `programsInDesktop` where you will see the programs that are listed.

If you need to change more things you will need some Vue knowledge :)

**Comment by shortymc** [comment]
Hi :)
I did it but it's still not working.
The original menu stay. also if let only the dist folder, it's working
 Or it's not working or it's looks like **a cache problem**.
I tried npm cache clean --force
and rm -rf node_modules/.cache
and nothing a changed
I try to reupload but nothing change.
I modify the files, maybe i've made a mistake.
You can download the modified files : https://www.tradezone.fr/media/files/Vuindows_fork.zip

 Thanks you for your support
Best regards

**Comment by marcmascarell** [comment]
You have to run `npm run dev` (on very change you make) or `npm run hot` on development. And then to optimize and minify use `npm run production`.

**Comment by shortymc** [comment]
Thanks you for fast responding ! :)
For npm run dev i got : 

------------------------------------
--------------------------------------

npm run dev

> vuindows@1.1.0 dev /var/www/html/tools/test6/00-00-00-Vuindows/tst3
> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/laravel-mix/setup/webpack.config.js'
Require stack:
- /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js
- /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireConfig (/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js:97:18)
    at /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js:102:15)
    at /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/webpack.js:171:41
    at Object.Yargs.self.parse (/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/yargs/yargs.js:533:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js',
    '/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuindows@1.1.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuindows@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-15T01_17_43_805Z-debug.log

>>> error log <<<

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v12.22.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vuindows@1.1.0~predev: vuindows@1.1.0
6 info lifecycle vuindows@1.1.0~dev: vuindows@1.1.0
7 verbose lifecycle vuindows@1.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vuindows@1.1.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/.bin:/usr/local/sbin:/usr/lo$
9 verbose lifecycle vuindows@1.1.0~dev: CWD: /var/www/html/tools/test6/00-00-00-Vuindows/tst3
10 silly lifecycle vuindows@1.1.0~dev: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'
10 silly lifecycle ]
11 silly lifecycle vuindows@1.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle vuindows@1.1.0~dev: Failed to exec dev script
13 verbose stack Error: vuindows@1.1.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid vuindows@1.1.0
15 verbose cwd /var/www/html/tools/test6/00-00-00-Vuindows/tst3
16 verbose Linux 4.9.0-15-amd64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.22.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error vuindows@1.1.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the vuindows@1.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


------------------------------------
------------------------------------

For npm run hot i got

--------------------------------------
----------------------------------------

npm run hot

> vuindows@1.1.0 hot /var/www/html/tools/test6/00-00-00-Vuindows/tst3
> cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/laravel-mix/setup/webpack.config.js'
Require stack:
- /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js
- /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireConfig (/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js:97:18)
    at /var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js:102:15)
    at Object.<anonymous> (/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack-dev-server/bin/webpack-dev-server.js:223:50)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack/bin/convert-argv.js',
    '/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuindows@1.1.0 hot: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuindows@1.1.0 hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-15T01_22_11_991Z-debug.log

>>> error log <<<

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'hot' ]
2 info using npm@6.14.4
3 info using node@v12.22.1
4 verbose run-script [ 'prehot', 'hot', 'posthot' ]
5 info lifecycle vuindows@1.1.0~prehot: vuindows@1.1.0
6 info lifecycle vuindows@1.1.0~hot: vuindows@1.1.0
7 verbose lifecycle vuindows@1.1.0~hot: unsafe-perm in lifecycle true
8 verbose lifecycle vuindows@1.1.0~hot: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/tools/test6/00-00-00-Vuindows/tst3/node_modules/.bin:/usr/local/sbin:/usr/lo$
9 verbose lifecycle vuindows@1.1.0~hot: CWD: /var/www/html/tools/test6/00-00-00-Vuindows/tst3
10 silly lifecycle vuindows@1.1.0~hot: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js'
10 silly lifecycle ]
11 silly lifecycle vuindows@1.1.0~hot: Returned: code: 1  signal: null
12 info lifecycle vuindows@1.1.0~hot: Failed to exec hot script
13 verbose stack Error: vuindows@1.1.0 hot: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid vuindows@1.1.0
15 verbose cwd /var/www/html/tools/test6/00-00-00-Vuindows/tst3
16 verbose Linux 4.9.0-15-amd64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "hot"
18 verbose node v12.22.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error vuindows@1.1.0 hot: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the vuindows@1.1.0 hot script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


---------------------------------------
----------------------------------------

 But if i load the url in my browser i don't need npm, ? It is working the same online without install. 
Thanks you for your help :)

**Comment by marcmascarell** [comment]
Yes you must use npm every time you make a change or it won't be reflected. If dependencies are not working make a pull to get the latest changes I made and reinstall them.

**Comment by shortymc** [comment]
Hi
I try your updated version.
It's not working with the index.html file without the file /dist/app.js
But if i add it the desktop is unchanged (like before)
after update dependencies and also add some more (see my pull request (the first on github!))
i can't run the app.

root@srv132:/var/www/html/tools/test6/00-00-00-Vuindows/js# npm run dev

> vuindows@1.1.0 dev /var/www/html/tools/test6/00-00-00-Vuindows
> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! vuindows@1.1.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vuindows@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-16T22_21_03_257Z-debug.log


>>> Error log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v12.22.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vuindows@1.1.0~predev: vuindows@1.1.0
6 info lifecycle vuindows@1.1.0~dev: vuindows@1.1.0
7 verbose lifecycle vuindows@1.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vuindows@1.1.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/tools/test6/00-00-00-Vuindows/node_modules/.bin:/usr/local/sbin:/usr/local/b$
9 verbose lifecycle vuindows@1.1.0~dev: CWD: /var/www/html/tools/test6/00-00-00-Vuindows
10 silly lifecycle vuindows@1.1.0~dev: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'
10 silly lifecycle ]
11 info lifecycle vuindows@1.1.0~dev: Failed to exec dev script
12 verbose stack Error: vuindows@1.1.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid vuindows@1.1.0
14 verbose cwd /var/www/html/tools/test6/00-00-00-Vuindows/js
15 verbose Linux 4.9.0-15-amd64
16 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "dev"
17 verbose node v12.22.1
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error vuindows@1.1.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
23 error spawn ENOENT
24 error Failed at the vuindows@1.1.0 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]


-------------------------------------------------------------
------------------------------------------------------------

npm run hot

> vuindows@1.1.0 hot /var/www/html/tools/test6/00-00-00-Vuindows
> cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js

sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! vuindows@1.1.0 hot: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vuindows@1.1.0 hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-16T22_29_00_880Z-debug.log
root@srv132:/var/www/html/tools/test6/00-00-00-Vuindows# nano /root/.npm/_logs/2021-05-16T22_29_00_880Z-debug.log
root@srv132:/var/www/html/tools/test6/00-00-00-Vuindows# 



>>> Error log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'hot' ]
2 info using npm@6.14.4
3 info using node@v12.22.1
4 verbose run-script [ 'prehot', 'hot', 'posthot' ]
5 info lifecycle vuindows@1.1.0~prehot: vuindows@1.1.0
6 info lifecycle vuindows@1.1.0~hot: vuindows@1.1.0
7 verbose lifecycle vuindows@1.1.0~hot: unsafe-perm in lifecycle true
8 verbose lifecycle vuindows@1.1.0~hot: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/tools/test6/00-00-00-Vuindows/node_modules/.bin:/usr/local/sbin:/usr/local/b$
9 verbose lifecycle vuindows@1.1.0~hot: CWD: /var/www/html/tools/test6/00-00-00-Vuindows
10 silly lifecycle vuindows@1.1.0~hot: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js'
10 silly lifecycle ]
11 info lifecycle vuindows@1.1.0~hot: Failed to exec hot script
12 verbose stack Error: vuindows@1.1.0 hot: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid vuindows@1.1.0
14 verbose cwd /var/www/html/tools/test6/00-00-00-Vuindows
15 verbose Linux 4.9.0-15-amd64
16 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "hot"
17 verbose node v12.22.1
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error vuindows@1.1.0 hot: `cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
23 error spawn ENOENT
24 error Failed at the vuindows@1.1.0 hot script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]


---------------------------
--------------------------

 Thanks for your support :)
 Best regards

**Comment by shortymc** [comment]
ok, i found a way to modify it, so i put it on my website. It's works well.
Thanks you very much :1st_place_medal: 
Best regards.
Come eat at home when you want :)

**Comment by shortymc** [comment]
Hello i will be in barcelona theses next days, i would like to encouter you
if you got some times for it.
Yo habla un poquito Espanol.

 Best Regards

Le dim. 9 janv. 2022 à 16:31, Marc Mascarell ***@***.***> a
écrit :
